### ISSUE TITLE
operator recipient must improve

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#1]
currently, operator calls ring two numbers until one answers. We need to be able to add more numbers, ideally stop ringing before voicemail picks up. Probably the best way is with a call queue.

**Comment by kra** [comment]
here's one strategy

https://wiki.asterisk.org/wiki/display/AST/Call+Pickup

operator call rings operator extension, which may or may not be connected to a phone

one extension connects user to operator extension
have a public incoming line with a passcode, or admin option on existing line, connect here
have internal extension that connects directly

when operator extension is ringing, notification occurs - text messages, direct calls
text message tells user to call incoming line or internal extension for operator call
direct call calls user, asks user to enter 1 for operator call, connects user to operator extension

**Comment by lboom** [comment]
Would the operator extension be a callgroup/pickup group? According to this article http://www.voip-info.org/wiki/view/Asterisk+callgroups+and+pickupgroups these are not intended to do multiple outbound calls.

If the operator extension is just going to be a AGI script or something similar that sends notification I don't think we will need to use the Pickup application for this.

**Comment by kra** [comment]
no, operator extension is just an extension, which is not even attached to a phone. Or maybe it is, whatever.

This is all based on my reading of those docs, I have not tried any of this, but:

calling user selects operator
dialplan rings operator extension, which probably is not picked up
operator users are notified (however this happens - phone, sms, chatroom, bot)
operator user selects diaplan context that calls CallPickup on ringing operator extension (howerver this happens - operator selects admin menu entry, or confbridge thing, or just picks up call)
call to operator extension is picked up, operator user and calling user are connected
