### ISSUE TITLE
jack not being loaded

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#100]
from startup logs

 [Aug 17 20:11:14] WARNING[1255] loader.c: Error loading module 'app_jack.so': libjack.so.0: cannot open shared object file: No such file or directory
    [Aug 17 20:11:14] WARNING[1255] loader.c: Module 'app_jack.so' could not be loaded.

**Comment by kra** [comment]
[futel@futel-stage ~]$ ls -l /usr/local/lib/libjack*
lrwxrwxrwx 1 root root      19 Aug 17 19:06 /usr/local/lib/libjacknet.so -> libjacknet.so.0.1.0
lrwxrwxrwx 1 root root      19 Aug 17 19:06 /usr/local/lib/libjacknet.so.0 -> libjacknet.so.0.1.0
-rwxr-xr-x 1 root root  154181 Aug 17 19:06 /usr/local/lib/libjacknet.so.0.1.0
lrwxrwxrwx 1 root root      22 Aug 17 19:06 /usr/local/lib/libjackserver.so -> libjackserver.so.0.1.0
lrwxrwxrwx 1 root root      22 Aug 17 19:06 /usr/local/lib/libjackserver.so.0 -> libjackserver.so.0.1.0
-rwxr-xr-x 1 root root 1046596 Aug 17 19:06 /usr/local/lib/libjackserver.so.0.1.0
lrwxrwxrwx 1 root root      16 Aug 17 19:06 /usr/local/lib/libjack.so -> libjack.so.0.1.0
lrwxrwxrwx 1 root root      16 Aug 17 19:06 /usr/local/lib/libjack.so.0 -> libjack.so.0.1.0
-rwxr-xr-x 1 root root  449999 Aug 17 19:06 /usr/local/lib/libjack.so.0.1.0
[futel@futel-stage ~]$

**Comment by kra** [comment]
ldconfig is run by install_misc.yml
but install_jackd is run after than
so it looks like we need to run install_jackd earlier? Or have a ldconfig in a later config recipe.

**Comment by x37v** [comment]
@kra to be safe we could just run ldconfig at the end of anywhere that needs it...
