### ISSUE TITLE
smaller secrets in ansible vault files

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#117]
ansible vault lets us have less unchecked in config, but it makes too much source opaque.

Instead of including whole file contents from the vault, only store variables and replace them in a template of some kind.

The easiest way would be to keep including file contents from ansible config, but template in variables, if that's possible. A better way might be to include files from the filesystem with template substitution, if that's possible.

**Comment by bnfinet** [comment]
Is this method of variable substitution helpful?

https://gist.github.com/tristanfisher/e5a306144a637dc739e7

Are you using ansible 1.9 or have you moved to the new stuff?

**Comment by kra** [comment]
That's what we're doing now, e.g.

https://github.com/kra/futel-installation/blob/master/asteriskserver/update_asterisk.yml#L68

the issue is that the secrets files are blobs as far as version control is concerned, which makes tracking changes and merges impossible, and is unwieldy for other reasons too.

The solution is to put less in the secrets files and template them in, possibly with some organizing of playbooks as we go.

**Comment by kra** [comment]
I'm using ansible 2.0 right now, but the README isn't specific on that (and several other things), which could be a hassle. Right now I think only one or zero other devs have built an up-to-date devbox, so it hasn't come up :)

have vagrant, virtualbox, ansible
vagrant plugin install vagrant-vbguest
