### ISSUE TITLE
put logwatch on vpnbox

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#13]
We will probably have the same notification spam issues as with asteriskbox, I think it's OK to just have something and work it out.

The openvpn routers are a weak spot, r2d2 was down for a while and we didn't know until they told us.

**Comment by kra** [comment]
logwatch is running on vpnbox, but it's currently not useful, it's showing the entire log each run.

**Comment by lboom** [comment]
Issue should be resolved with logrotate properly configured.
