### ISSUE TITLE
restrict vpn traffic

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#185]
vpn lets all outgoing traffic through, but clients only need to talk to futel-prod and futel-stage.

**Comment by kra** [comment]
and futel-dev

**Comment by todgru** [comment]
any specifics for this change, like ports or ips? stage vs prod?

**Comment by kra** [comment]
I think all traffic to the hosts is ok. The main motivation is just to stop somebody from plugging a cable into one of our vpn client boxen and then routing all their traffic through our vpn.

The only thing connected to a vpn client should be a SIP client., and a SIP client only needs to talk to the asterisk server. The asterisk server then talks to providers and other services directly, as well as back to the clients.

The asterisk server is on futel-prod.phu73l.net, or futel-stage, or futel-dev.

Allowing any subdomain of phu73l.net might be easiest and best.

The vpn setup is maybe a bit weird. Only the SIP clients are behind vpn clients. The asterisk server doesn't have a vpn client and doesn't really know there's a vpn, it just talks back using the connection the sip client opens. It would probably be best for everything to have a client - then we might be able to retire phu73l.net altogether, and our deploy might be smoother. But that's a bigger change, I just don't want our clients to let inappropriate traffic through the vpn.

**Comment by kra** [comment]
moved to https://github.com/kra/futel-vpnbox/issues/1
