### ISSUE TITLE
thump at the end of every converted audio file

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#234]
After running audio through update_audio_assets.rb, there's a noise at the end of each one.

[audio.zip](https://github.com/kra/futel-installation/files/2659032/audio.zip)

**Comment by kra** [comment]
The ansible build is what does the conversion and exports to the asteriskserver source tree.

Every file in the assets repo should be in use.

That recording is playing assets in the recordings directory, which is .sln files exported from .gsm files. I don't know if the other types get the thunk also.

**Comment by x37v** [comment]
@kra the files generated on my machine via:
`ansible-playbook -i deploy/hosts update_assets_playbook.yml`

Do not produce the thud.
Can you send me a copy of the following files from your setup?
```
src/var/lib/asterisk/sounds/futel/recordings/karl_quuux/press-one.sln
src/var/lib/asterisk/sounds/futel/recordings/karl_quuux/to-make-a-call.sln
```

**Comment by x37v** [comment]
@kra it seems that I overlooked that asterisk wants the generated `.sln` files to be *raw* aka headerless.

I have a PR up that removes the headers from these files.

**Comment by kra** [comment]
This didn't work for me.

- Cloned raw-audio branch
- built and deployed by following instructions in asterisk-server/README.virtualbox
-- I think the relevant action is "ansible-playbook -i deploy/hosts update_assets_playbook.yml"
- listened to a menu by using linphone client
- thump at end of every sound file in menu

**Comment by kra** [comment]
that repro might not be useful for you at this time, if you can describe how to run and demo the process maybe we can do that. But hopefully it uses the same local build steps as that playbook.

**Comment by x37v** [comment]
@kra did you do a `make clean` before deploying the audio assets? I still don't know how to create a VM that I can dial into to test this.. 
https://github.com/kra/futel-installation/issues/259

**Comment by kra** [comment]
Yes, I did, I followed the process in README and README.virtualbox.

Can you please attempt to follow the README.virtualbox as described in #259 and tell me where you are blocked? You will need to be able to receive two secrets files from me, how do you want them to be sent securely? Lastpass, keybase?

**Comment by x37v** [comment]
So the latest merge resolved the thump?
