### ISSUE TITLE
audio levels not consistent for recordings

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#257]
wildcard line and church of robotron much quieter than menu statements

**Comment by kra** [comment]
mp3s are not normalized

normalization is done with scripts/update_audio_assets.rb
normalization is systemed out to a normalize-audio command
this could do mp3s, is there a reason we didn't?

**Comment by kra** [comment]
mp3s are now normalized, but wildcard line is still quieter.

We are using normalize-audio with --peak, which I thought was what we wanted, "edit the peak volume to be this maximum and scale everything to that". Do we want something different? We don't need much range, can we combine a peak and an average?

**Comment by x37v** [comment]
@kra `--peak` ends up making individual recordings as loud as they can be, there are other modes to try to make multiple files consistent with eachother, but nothing is going to make an individual file louder than `--peak`

can you indicate mp3 files that you think *are* loud enough and some that aren't?

My guess is that we just have to compress the wildcard line recordings... basically, make the louder parts not as loud and the quieter parts louder so that the volume of everything seems louder all together.

**Comment by x37v** [comment]
@kra see what you think about this:  http://dump.x37v.info/6-compressed.mp3 compared to the original.

If you think that is good then if you give me the originals (before you made them mp3s) I can apply the same processing to all of the wildcard line.

**Comment by kra** [comment]
Every one of the few mp3s I listened to was noticibly quieter than the menu recordings. I listened to a couple of wildcard line sounds and robotron sermons.

Hearability is more important than quality for the phone interface.

**Comment by kra** [comment]
To elaborate, lowering the relative volume of louder effects or clicks or whatever, so that the overall volume (and hopefully the important part, the spoken content) gets normalized to be similar to the menu recordings, is a good solution.

http://dump.x37v.info/6-compressed.mp3 is overall louder than the existing 6.mp3, so it is probably what we want.

If we could do this in the normalization step and not have to worry about levels in the source - allowing future shoddy input to be workable - that's ideal. But if we have to massage the source, we can do that.

Other than a .flac for episode 3, the mp3s in the futel-content repo on gitlab are the most original files I have.

**Comment by kra** [comment]
nice
