### ISSUE TITLE
implement hunt the wumpus

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#284]
this game can probably be done through audio only
link to elite rewards area of #84

**Comment by kra** [comment]
https://www.filfre.net/2011/05/hunt-the-wumpus-part-2/

**Comment by lboom** [comment]
I have a rough draft of the game rules(as close to the original as possible):
- arrows
  player carries 5 arrows, once gone player loses
  1-5 rooms
  prompt for number of rooms and accept input
  for each move, enter room(check for player, wumpus)
  random choice of next if room is invalid
  if hit wumpus, you win
  if hit player, you lose

- wumpus
  if player lands on wumpus room
  wumpus wakes
  .75 chance that a) moves 1 room
  .25 chance that b) stays
  if stay, you dead
  if move, continue as normal(check for other hazards etc)

- bats
  if player lands on bats room
  bats carries to ANY random room(not same room to avoid annoying player)

- pits
  if player lands on pits room
  instant death(unless wumpus gets them first)

**Comment by lboom** [comment]
This has been merged.
