### ISSUE TITLE
openvpn is not logging usefully

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#29]
openvpn is not logging to /var/log/openvpn.log or /var/log/messages.

openvpn appears to be logging to /var/log/openvpn_old/openvpn.log-20150626. That file contains logs from June 25 and July 1, with nothing in between.

The messages in that file are not getting into logwatch.

**Comment by lboom** [comment]
Probably fixed with "copytruncate" added to logrotate. We need to run a test box for a day or two.

**Comment by kra** [comment]
getting pages of unprintable characters at the beginning. Looking at the old logs, it grows daily? I deleted the current openvpn log file on the stage openvpn box, but it didn't magically fix itself.

**Comment by lboom** [comment]
Openvpn doesn't like anything messing with it's logs.
