### ISSUE TITLE
operator or crosstalk leads to girl from ipanema

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#32]
picked up ext 667 in response to a ring, heard girl from ipanema.

Looks like the ring was due to an operator call.

From the logs, it looks like this is some kind of crosstalk between calls - maybe one call was playing that and when I picked up 667, I connected to that call somehow? I have been able to do that before by flashing over and over again, but never reproducibly.

Here's the logs from then, maybe not from the beginning of everything. It looks like call 46 was ringing the street phone, call 48 called the operator, then when I picked up the operator ring I got connected to 46, which had been playing hold music? Maybe?

[Sep 27 13:07:27] VERBOSE[1454][C-00000048] netsock2.c:   == Using SIP RTP CoS mark 5
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [999@default-outgoing:1] Set("SIP/668-00000079", "destination=outgoing-ivr") in new stack
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [999@default-outgoing:2] Goto("SIP/668-00000079", "default-outgoing-by-extension,s,1") in new stack
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Goto (default-outgoing-by-extension,s,1)
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@default-outgoing-by-extension:1] Macro("SIP/668-00000079", "metric,outgoing-by-extension") in new stack
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@macro-metric:1] AGI("SIP/668-00000079", "metric.agi,outgoing-by-extension") in new stack
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/metric.agi
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] res_agi.c:  metric.agi,outgoing-by-extension: CALLERID(number)=668, UNIQUEID=1443384447.121, CHANNEL=SIP/668-00000079, name=outgoing-by-extension
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] res_agi.c:     -- <SIP/668-00000079>AGI Script metric.agi completed, returning 0
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@default-outgoing-by-extension:2] Set("SIP/668-00000079", "CALLERID(num)=18452055004") in new stack
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@default-outgoing-by-extension:3] Goto("SIP/668-00000079", "outgoing-ivr,s,1") in new stack
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Goto (outgoing-ivr,s,1)
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@outgoing-ivr:1] Macro("SIP/668-00000079", "metric,outgoing-ivr") in new stack
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@macro-metric:1] AGI("SIP/668-00000079", "metric.agi,outgoing-ivr") in new stack
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/metric.agi
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] res_agi.c:  metric.agi,outgoing-ivr: CALLERID(number)=18452055004, UNIQUEID=1443384447.121, CHANNEL=SIP/668-00000079, name=outgoing-ivr
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] res_agi.c:     -- <SIP/668-00000079>AGI Script metric.agi completed, returning 0
[Sep 27 13:07:27] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@outgoing-ivr:2] WaitExten("SIP/668-00000079", "0.25") in new stack
[Sep 27 13:07:28] VERBOSE[2715][C-00000046] app_dial.c:     -- SIP/callcentric-default-00000078 is ringing
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] pbx.c:     -- Timeout on SIP/668-00000079, continuing...
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@outgoing-ivr:3] Macro("SIP/668-00000079", "say,welcome-to-fewtel") in new stack
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@macro-say:1] AGI("SIP/668-00000079", "sound_path.agi,welcome-to-fewtel,outgoing-ivr") in new stack
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/sound_path.agi
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] res_agi.c:     -- <SIP/668-00000079>AGI Script sound_path.agi completed, returning 0
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@macro-say:2] BackGround("SIP/668-00000079", "/opt/asterisk/var/lib/asterisk/sounds/futel/recordings/karl_quuux/welcome-to-fewtel") in new stack
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] file.c:     -- <SIP/668-00000079> Playing '/opt/asterisk/var/lib/asterisk/sounds/futel/recordings/karl_quuux/welcome-to-fewtel.gsm' (language 'en')
[Sep 27 13:07:28] VERBOSE[2715][C-00000046] app_dial.c:     -- SIP/callcentric-default-00000078 is ringing
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] pbx.c:     -- Invalid extension '5' in context 'outgoing-ivr' on SIP/668-00000079
[Sep 27 13:07:28] VERBOSE[2755][C-00000048] pbx.c:   == CDR updated on SIP/668-00000079
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [i@outgoing-ivr:1] Goto("SIP/668-00000079", "s,2") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Goto (outgoing-ivr,s,2)
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@outgoing-ivr:2] WaitExten("SIP/668-00000079", "0.25") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Timeout on SIP/668-00000079, continuing...
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@outgoing-ivr:3] Macro("SIP/668-00000079", "say,welcome-to-fewtel") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@macro-say:1] AGI("SIP/668-00000079", "sound_path.agi,welcome-to-fewtel,outgoing-ivr") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/sound_path.agi
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] res_agi.c:     -- <SIP/668-00000079>AGI Script sound_path.agi completed, returning 0
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@macro-say:2] BackGround("SIP/668-00000079", "/opt/asterisk/var/lib/asterisk/sounds/futel/recordings/karl_quuux/welcome-to-fewtel") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] file.c:     -- <SIP/668-00000079> Playing '/opt/asterisk/var/lib/asterisk/sounds/futel/recordings/karl_quuux/welcome-to-fewtel.gsm' (language 'en')
[Sep 27 13:07:29] VERBOSE[2715][C-00000046] app_dial.c:     -- SIP/callcentric-default-00000078 is ringing
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] app_macro.c:   == Channel 'SIP/668-00000079' jumping out of macro 'say'
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [0@outgoing-ivr:1] Goto("SIP/668-00000079", "operator,s,1") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Goto (operator,s,1)
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@operator:1] Macro("SIP/668-00000079", "metric,operator") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@macro-metric:1] AGI("SIP/668-00000079", "metric.agi,operator") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/metric.agi
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] res_agi.c:  metric.agi,operator: CALLERID(number)=18452055004, UNIQUEID=1443384447.121, CHANNEL=SIP/668-00000079, name=operator
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] res_agi.c:     -- <SIP/668-00000079>AGI Script metric.agi completed, returning 0
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] pbx.c:     -- Executing [s@operator:2] Dial("SIP/668-00000079", "SIP/667&SIP/callcentric-default/15038419766&SIP/callcentric-default/15033090849,300") in new stack
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] netsock2.c:   == Using SIP RTP CoS mark 5
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] netsock2.c:   == Using SIP RTP CoS mark 5
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] netsock2.c:   == Using SIP RTP CoS mark 5
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] app_dial.c:     -- Called SIP/667
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] app_dial.c:     -- Called SIP/callcentric-default/15038419766
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] app_dial.c:     -- Called SIP/callcentric-default/15033090849
[Sep 27 13:07:29] VERBOSE[1454][C-00000048] chan_sip.c:     -- Got SIP response 486 "Busy Here" back from 45.55.19.71:5061
[Sep 27 13:07:29] VERBOSE[2755][C-00000048] app_dial.c:     -- SIP/667-0000007a is busy
[Sep 27 13:07:31] VERBOSE[2715][C-00000046] app_dial.c:     -- SIP/callcentric-default-00000078 is ringing
[Sep 27 13:07:31] VERBOSE[2755][C-00000048] app_dial.c:     -- SIP/callcentric-default-0000007c is ringing
[Sep 27 13:07:31] VERBOSE[2755][C-00000048] app_dial.c:     -- SIP/callcentric-default-0000007c answered SIP/668-00000079
[Sep 27 13:07:31] VERBOSE[2755][C-00000048] rtp_engine.c:     -- Locally bridging SIP/668-00000079 and SIP/callcentric-default-0000007c
[Sep 27 13:07:32] WARNING[1454] chan_sip.c: Retransmission timeout reached on transmission 0af7516f09e895d12e52b1593a551d85@callcentric.com for seqno 102 (Critical Request) -- See https://wiki.asterisk.org/wiki/display/AST/SIP+Retransmissions
Packet timed out after 6400ms with no response
[Sep 27 13:07:32] WARNING[1454] chan_sip.c: Hanging up call 0af7516f09e895d12e52b1593a551d85@callcentric.com - no reply to our critical packet (see https://wiki.asterisk.org/wiki/display/AST/SIP+Retransmissions).
[Sep 27 13:07:32] VERBOSE[2715][C-00000046] res_musiconhold.c:     -- Stopped music on hold on SIP/callcentric-default-00000077
[Sep 27 13:07:34] VERBOSE[2715][C-00000046] app_dial.c:     -- SIP/667-00000076 answered SIP/668-00000074
[Sep 27 13:07:34] VERBOSE[2715][C-00000046] res_musiconhold.c:     -- Stopped music on hold on SIP/callcentric-default-00000078
[Sep 27 13:07:34] VERBOSE[2715][C-00000046] rtp_engine.c:     -- Locally bridging SIP/668-00000074 and SIP/667-00000076
[Sep 27 13:07:34] WARNING[2715][C-00000046] channel.c: Codec mismatch on channel SIP/667-00000076 setting write format to slin from ulaw native formats (ulaw)
[Sep 27 13:07:36] VERBOSE[2755][C-00000048] pbx.c:   == Spawn extension (operator, s, 2) exited non-zero on 'SIP/668-00000079'
[Sep 27 13:07:45] VERBOSE[2715][C-00000046] res_musiconhold.c:     -- Stopped music on hold on SIP/667-00000076
[Sep 27 13:07:45] VERBOSE[2715][C-00000046] pbx.c:   == Spawn extension (operator, s, 2) exited non-zero on 'SIP/668-00000074'
[Sep 27 13:08:08] VERBOSE[1454][C-00000049] netsock2.c:   == Using SIP RTP CoS mark 5
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [999@default-outgoing:1] Set("SIP/667-0000007d", "destination=outgoing-ivr") in new stack
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [999@default-outgoing:2] Goto("SIP/667-0000007d", "default-outgoing-by-extension,s,1") in new stack
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Goto (default-outgoing-by-extension,s,1)
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@default-outgoing-by-extension:1] Macro("SIP/667-0000007d", "metric,outgoing-by-extension") in new stack
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@macro-metric:1] AGI("SIP/667-0000007d", "metric.agi,outgoing-by-extension") in new stack
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/metric.agi
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] res_agi.c:  metric.agi,outgoing-by-extension: CALLERID(number)=667, UNIQUEID=1443384488.125, CHANNEL=SIP/667-0000007d, name=outgoing-by-extension
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] res_agi.c:     -- <SIP/667-0000007d>AGI Script metric.agi completed, returning 0
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@default-outgoing-by-extension:2] Set("SIP/667-0000007d", "CALLERID(num)=5037414912") in new stack
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@default-outgoing-by-extension:3] Goto("SIP/667-0000007d", "outgoing-ivr,s,1") in new stack
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Goto (outgoing-ivr,s,1)
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@outgoing-ivr:1] Macro("SIP/667-0000007d", "metric,outgoing-ivr") in new stack
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@macro-metric:1] AGI("SIP/667-0000007d", "metric.agi,outgoing-ivr") in new stack
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/metric.agi
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] res_agi.c:  metric.agi,outgoing-ivr: CALLERID(number)=5037414912, UNIQUEID=1443384488.125, CHANNEL=SIP/667-0000007d, name=outgoing-ivr
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] res_agi.c:     -- <SIP/667-0000007d>AGI Script metric.agi completed, returning 0
[Sep 27 13:08:08] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@outgoing-ivr:2] WaitExten("SIP/667-0000007d", "0.25") in new stack
[Sep 27 13:08:09] VERBOSE[2761][C-00000049] pbx.c:     -- Timeout on SIP/667-0000007d, continuing...
[Sep 27 13:08:09] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@outgoing-ivr:3] Macro("SIP/667-0000007d", "say,welcome-to-fewtel") in new stack
[Sep 27 13:08:09] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@macro-say:1] AGI("SIP/667-0000007d", "sound_path.agi,welcome-to-fewtel,outgoing-ivr") in new stack
[Sep 27 13:08:09] VERBOSE[2761][C-00000049] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/sound_path.agi
[Sep 27 13:08:09] VERBOSE[2761][C-00000049] res_agi.c:     -- <SIP/667-0000007d>AGI Script sound_path.agi completed, returning 0
[Sep 27 13:08:09] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@macro-say:2] BackGround("SIP/667-0000007d", "/opt/asterisk/var/lib/asterisk/sounds/futel/recordings/karl_quuux/welcome-to-fewtel") in new stack
[Sep 27 13:08:09] VERBOSE[2761][C-00000049] file.c:     -- <SIP/667-0000007d> Playing '/opt/asterisk/var/lib/asterisk/sounds/futel/recordings/karl_quuux/welcome-to-fewtel.gsm' (language 'en')
[Sep 27 13:08:11] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@outgoing-ivr:4] Macro("SIP/667-0000007d", "say,to-make-a-call") in new stack
[Sep 27 13:08:11] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@macro-say:1] AGI("SIP/667-0000007d", "sound_path.agi,to-make-a-call,outgoing-ivr") in new stack
[Sep 27 13:08:11] VERBOSE[2761][C-00000049] res_agi.c:     -- Launched AGI Script /opt/asterisk/var/lib/asterisk/agi-bin/sound_path.agi
[Sep 27 13:08:11] VERBOSE[2761][C-00000049] res_agi.c:     -- <SIP/667-0000007d>AGI Script sound_path.agi completed, returning 0
[Sep 27 13:08:11] VERBOSE[2761][C-00000049] pbx.c:     -- Executing [s@macro-say:2] BackGround("SIP/667-0000007d", "/opt/asterisk/var/lib/asterisk/sounds/futel/recordings/karl_quuux/to-make-a-call") in new stack
[Sep 27 13:08:11] VERBOSE[2761][C-00000049] file.c:     -- <SIP/667-0000007d> Playing '/opt/asterisk/var/lib/asterisk/sounds/futel/recordings/karl_quuux/to-make-a-call.gsm' (language 'en')
[Sep 27 13:08:11] VERBOSE[2761][C-00000049] app_macro.c:   == Spawn extension (macro-say, s, 2) exited non-zero on 'SIP/667-0000007d' in macro 'say'
[Sep 27 13:08:11] VERBOSE[2761][C-00000049] pbx.c:   == Spawn extension (outgoing-ivr, s, 4) exited non-zero on 'SIP/667-0000007d'
[root@futel-prod ~]#

**Comment by lboom** [comment]
The default hold music is currently set to "Girl from Ipanema", but when someone rings the operator they should be hearing a ring. If you flash the hook on an extension you will spawn a new call. Doing this repeatedly may connect you to one of the calls, or possibly trigger hold. Perhaps a caller decided against calling the operator and flashed to make a different call and that may have led to placing the previous call on hold? Possibly we can remove multiple calls from a single extension to help this, seems like any call not currently connected is dropped into hold.

**Comment by kra** [comment]
#157 might fix this if we do that?
