### ISSUE TITLE
progged game is leaving leftover audio play processes

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#334]
play progged one or two times
hang up or finish or whatever
there are still audio play processes running
top or ps -u asterisk should show them
I think the progged process is still running also?
Is this happening to all agi processes? This may be the first one that runs forever until killed, maybe record.agi and others also do this but its just a wait_for_digit thats left over?

**Comment by lboom** [comment]
I am seeing leftover 'mpg123' procs after making a recording set or two... this seems likely to be an agi issue in general.

**Comment by kra** [comment]
if they go away eventually, NBD - I was seeing them change after I hung up, like the AGI file was still running

**Comment by lboom** [comment]
ah, on a closer look I think I was being tricked by the operator and hold music:
```asterisk 13889  0.0  0.3  11980  3056 ?        S    22:32   0:00 mpg123 -q -s --mono -r 8000 -b 2048 -f 4096 ipanema.mp3
asterisk 13891  0.0  0.3  11980  3052 ?        S    22:32   0:00 mpg123 -q -s --mono -r 8000 -b 2048 -f 4096 operator.mp3
asterisk 13894  0.0  0.0  11980   396 ?        S    22:32   0:00 mpg123 -q -s --mono -r 8000 -b 2048 -f 4096 ipanema.mp3
asterisk 13895  0.0  0.0  11980   396 ?        S    22:32   0:00 mpg123 -q -s --mono -r 8000 -b 2048 -f 4096 operator.mp3
