### ISSUE TITLE
implement conference oracle game

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#336]
pick an hour to staff the conference line

pick a rng to compute password, for example mailbox ^^ 3 minus 132 mod 1000. Or use mailbox as a seed for a real rng, whatever.

when user visits game, "visit the conference between HOUR and HOUR for access". Then prompt for password.

Conference staffer is available during hour to compute passwords for users. Staffer may act mysterious or stupid or whatever.

**Comment by kra** [comment]
fun thing about this one is other people can spoof the conference staffer or otherwise grief the users

**Comment by lboom** [comment]
reopening because the merge closed it... sigh. We still need to implement the menu items for this.
