### ISSUE TITLE
wumpus game needs intro

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#339]
tell user some background 
for example user is trying to shoot wumpus before landing on it, does wumpus move, etc
statements may indicate nearby perils?
arrows may move randomly?

we can work out text for this

**Comment by kra** [comment]
also maybe some history
"first introduced on the foobar system in 197dickety by this person"

**Comment by breedx2** [comment]
There is an initial stab at this:

```
Hunt the Wumpus is a turn-based adventure game,
originally made by Gregory Yob in 1973.

Your quest is to hunt the horrible Wumpus through
a series of caves in order to kill it with one
of your crooked arrows.  Each cave has a number
and is connected to 3 other caves.  On each turn,
you will move to another cave or shoot an arrow
into an adjacent cave. Beware! You may find caves
with pits that kill you, or you might be carried
to a random cave by a team of super bats. If you
enter a cave with the Wumpus, it will choose to
eat you, or it will run away.

Good luck and happy adventuring!
```

I made [a TTS sound file of this over here](http://noisybox.net/wumpus_intro.wav). It's 40 seconds, which might be a little on the long side.  If we tweak the wording/phrasing/text I can rebuild it pretty quickly/easily...or we could have it recorded in the same voice as the other prompts.  Let me know what you think!

**Comment by kra** [comment]
Looks good to me. If Anzie can record it, great, otherwise we can use yours.

**Comment by lboom** [comment]
The script is great! I will make another recording for it tonight and update the extension for the game so we can make it skippable.
