### ISSUE TITLE
packaging of intermediate devbox images is busted

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#35]
this is for the first intermediate devbox, baseinstall, which doesn't have any configuration changes. I wonder if this is related to 'yum update' now ending up with a centos 6.7 box when the base box is centos 6.5.

karl@dispater:~/Documents/futel-installation/asteriskserver$ src/repackage_vm.sh asteriskserver centos6_32_baseinstall ../centos6_32_baseinstall.box
+ boxtype=asteriskserver
+ boxname=centos6_32_baseinstall
+ boxfilename=../centos6_32_baseinstall.box
++ dirname src/repackage_vm.sh
+ scriptdir=src
+ export vagrantbox=centos6_32_baseinstall
+ vagrantbox=centos6_32_baseinstall
+ vagrant up --no-provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos6_32_baseinstall'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: asteriskserver_default_1446665299533_75165
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
    default: Adapter 3: bridged
    default: Adapter 4: bridged
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by lboom** [comment]
This seems similar https://github.com/mitchellh/vagrant/issues/5186
I have tried using: config.ssh.insert_key = false in the Vagrantfile and so far have had no luck

**Comment by lboom** [comment]
We aren't doing this anymore...
