### ISSUE TITLE
konami game is not finding sounds

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#350]
it re-implements util.say but I forget why, it's because util.say messes with the escape argument?

What is intended? Play sound, if key pressed return key, if not return ""? What are the valid keys?

**Comment by lboom** [comment]
When I replace the konami sounds with 8k files the game finds the sounds without issue and plays to completion.

**Comment by lboom** [comment]
With the current batch of 16k files we have in our content repo I see this error when the game(or any game using similar files starts):
```
[Jun 20 21:48:57] WARNING[30840][C-00000004]: format_wav.c:113 check_header_fmt: Unexpected frequency mismatch 16000 (expecting 8000)```

**Comment by breedx2** [comment]
`util.say()` doesn't account for the fourth column tones `A` and `B`.

**Comment by lboom** [comment]
https://community.asterisk.org/t/question-about-playback-audio-formats/83928
This is on a newer version of asterisk, but seems to be exactly the same issue. Apparently naming matters and a "wav16" file extension works... but I suspect that this would need to be tackled in utils as well.

**Comment by kra** [comment]
I'm not getting the same warnings, and I you're getting them on all the wumpus files too, right? Do you get other effects when you get the warnings or do you get the generated voice?

**Comment by lboom** [comment]
wumpus files work fine as they are. I am able to move them and force the generated files as well. No warnings on hunt the wumpus.
