### ISSUE TITLE
packer build for image creation

### ISSUE THREAD

**Issue by lboom** [kra/futel-installation#403]
First step is to create a base image that can be deployed to and pushing to digital ocean

**Comment by lboom** [comment]
Listing images is simple enough using the digital ocean API
`https://developers.digitalocean.com/documentation/v2/#list-all-images`
The resulting list contains the regions that the images are available in... this will include regions that are not currently available

**Comment by kra** [comment]
would be good to have a MVP/demo from start through baseinstall_playbook

https://github.com/kra/futel-installation/blob/master/asteriskserver/README#L28

stage box could still require the direct ansible deploy_digitalocean_playbook manually run first, if necessary
