### ISSUE TITLE
verify that events don't contain sensitive information

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#409]
outgoing numbers dialed
incoming caller id
(callerid of futel phones are not sensitive)
voicemail box numbers

what else

should we anonymize the extensions
maybe anonymize everything but a whitelist of public extensions

**Comment by kra** [comment]
it doesn't look like arbitrary dtmf gets in there but that would be bad

**Comment by breedx2** [comment]
The events going into SNS -> SQS definitely do contain incoming calling ID numbers.  Pretty sure that outbound numbers are in there too.

Are you wanting to obfuscate this stuff _before_ it hits SNS then?

**Comment by kra** [comment]
That's a good question. Right now only trusted people are receiving them. But it would be good to allow anyone to receive them, not worry about popped boxes, etc. And it's easier to do this on the server, keep everything together.

**Comment by kra** [comment]
maybe the best place to do this is when creating the metric instances which get turned into events among other things
it would be a win to make the metric logs themselves clean if they have sensitive data also

CALLERID(number) is written to the metric log, but be sure that this isn't being re-used as a different identifier

bleh it looks like metrics only cause an event by executing UserEvent(name), so the asterisk event may contain callerid automagically, we may need to clean where the eventlistener catches the event and publishes

**Comment by kra** [comment]
we have verified that sensitive information is in the events, #411 will fix this
