### ISSUE TITLE
test various voicemail

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#419]
a regular user reported that something about voicemail wasn't working
run through the voicemail tests on prod
create, leave a message, check messages, add greeting, leave a message, check messages
also leave and check for box 1337

**Comment by breedx2** [comment]
For future selves, "tests on prod" might refer to the steps in the testplan, which is a google sheet linked to from here https://github.com/kra/futel-installation/blob/49efb4bbdb43b8bb2225b8182948dc25169ef6fe/asteriskserver/README.testplan.

Right now it has these tests and the following last confirmed dates:

voicemail: |  
-- | --
can create voicemail box | 2021-04-07
can leave voicemail | 2021-04-07
can check voicemail | 2021-04-07
can hear voicemail info | 2021-04-07
can attempt to check, leave voicemail for invalid mailbox | 2021-04-07
  |  
outgoing voicemail: |  
can access all voicemail menu items | 2021-04-07
  |  
incoming voicemail: |  
can access all voicemail menu items except create voicemail | 2019-08-04

**Comment by breedx2** [comment]
Wish we knew what the specific voicemail issue was.  I can probably try at a phone this week.

**Comment by kra** [comment]
Yeah the testplan is executed on stage, I mean it would be good to whip through some tests on prod, both because I don't know when the next prod will be, and in case there's a weird issues where the final sync to prod is breaking something.

We don't have to follow the testplan, but it's a good framework.

I can give you creds and help you set up a softphone so you don't need to find a phone if you don't want to. I don't have a phone myself yet :)
