### ISSUE TITLE
asterisk conf provision takes too long

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#428]
we remove all existing then upload our conf, this makes development take longer than necessary, can we just say "directory should only contain these files", then we may be able to skip upload of files not needing change

**Comment by kra** [comment]
we probably don't  need the delete step at all

**Comment by lboom** [comment]
https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html#examples
this is worth a try. will need to ensure rsync is installed on both local and remote

**Comment by lboom** [comment]
rsyncing these might end up causing issues during packer build steps. continued work to reduce modules and asterisk default files is probably enough to reduce time on this step.
