### ISSUE TITLE
asteriskbox has weird duplicate log directory tree

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#45]
Logrotate? This is at least using up rsync bandwidth. I didn't diff the contents.

Listing is from the backup, but the dates are similar on prod, and on older backups.

karl@eurydice:/opt/futel/backups/prod/2016-01/opt/asterisk/var/log$ ls -l /opt/futel/backups/prod/2015-12/opt/asterisk/var/log/asterisk
total 6272
drwxr-xr-x 7 nobody 500    4096 Dec 16 17:19 asterisk
drwxr-xr-x 2 nobody 500    4096 Dec 16 17:12 cdr-csv
drwxr-xr-x 2 nobody 500    4096 Dec 16 17:12 cdr-custom
drwxr-xr-x 2 nobody 500    4096 Dec 16 17:12 cel-custom
-rw-r--r-- 1 nobody 500  120744 Dec 31 03:18 debug
-rw-r----- 1 nobody 500 6263617 Dec 31 06:37 messages
-rw-r----- 1 nobody 500       0 Dec 31 03:18 metrics
drwxr-xr-x 2 nobody 500   12288 Dec 31 03:18 old
-rw-r----- 1 nobody 500      40 Dec 31 03:18 queue_log
karl@eurydice:/opt/futel/backups/prod/2016-01/opt/asterisk/var/log$ ls -l /opt/futel/backups/prod/2015-12/opt/asterisk/var/log/asterisk/asterisk/
total 328
drwxr-xr-x 6 nobody 500   4096 Dec 16 17:19 asterisk
drwxr-xr-x 2 nobody 500   4096 Dec 16 17:12 cdr-csv
drwxr-xr-x 2 nobody 500   4096 Dec 16 17:12 cdr-custom
drwxr-xr-x 2 nobody 500   4096 Dec 16 17:12 cel-custom
-rw-r--r-- 1 nobody 500 115128 Dec 16 17:19 debug
-rw-r----- 1 nobody 500 184191 Dec 16 17:19 messages
-rw-r----- 1 nobody 500   7939 Dec 16 17:19 metrics
drwxr-xr-x 2 nobody 500   4096 Dec 16 17:19 old
-rw-r----- 1 nobody 500     40 Dec 16 17:19 queue_log
karl@eurydice:/opt/futel/backups/prod/2016-01/opt/asterisk/var/log$ ls -l /opt/futel/backups/prod/2015-12/opt/asterisk/var/log/asterisk/asterisk/asterisk/
total 136
drwxr-xr-x 2 nobody 500   4096 Dec 16 17:19 cdr-csv
drwxr-xr-x 2 nobody 500   4096 Dec 16 17:19 cdr-custom
drwxr-xr-x 2 nobody 500   4096 Dec 16 17:19 cel-custom
-rw-r--r-- 1 nobody 500 110916 Dec 16 17:19 debug
-rw-r----- 1 nobody 500   1673 Dec 16 17:19 messages
-rw-r----- 1 nobody 500      0 Dec 16 17:19 metrics
drwxr-xr-x 2 nobody 500   4096 Dec 16 17:19 old
-rw-r----- 1 nobody 500     40 Dec 16 17:19 queue_log
karl@eurydice:/opt/futel/backups/prod/2016-01/opt/asterisk/var/log$

**Comment by lboom** [comment]
promote_stage.sh is being run twice during setup. we were doing this:
$SSH futel@$stage_ip "sudo -u asterisk cp -r /tmp/stage/asterisk /opt/asterisk/var/log/asterisk"
which was creating a sub directory in the existing log directory.

**Comment by kra** [comment]
reverted https://github.com/kra/futel-installation/commit/533ec4d7a083fbcdc9b1b45f1e6f55bedbcacd86#diff-ddedceb67222c11859515d6cf65ee143 and https://github.com/kra/futel-installation/commit/12c12611664ee7dae6fd6dcf4746928920ef00c1

**Comment by kra** [comment]
let's copy less things over - instead of all of log/asterisk, copy only the logfiles we care about - messages, metrics, and old/*

Keep replacing the voicemail dir because we want to blow away any existing voicemail content.

That's not perfect, but we can put off a real migration for a long time! We'd probably want to have real storage for these metrics and assets, hopefully needing to care about that is far in the future!

**Comment by kra** [comment]
hopefully fixed by https://github.com/kra/futel-installation/commit/676554fa2d04de73ec878cfcc94e12a1fee7feb7
