### ISSUE TITLE
rename all extensions to location

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#462]
all extension names should reference only location eg "cesar chavez" "hedron" "clinton". Some currently have human names.

These are now being written to web pages we expect people to read and ask questions about

**Comment by kra** [comment]
do this for all contexts and metrics

**Comment by breedx2** [comment]
Tracking e9f99956c26977eeb36df86e92e7c2d0b1cfe321 e19b151b9e863a164833166467ac19a5ceeae261 064be2e5d38eae83593e01415cdb2fe547a0d79c
