### ISSUE TITLE
pound key ends operator call

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#54]
Accept operator call, then hit pound. Operator is hung up on. Caller gets ipanema, then call is ended after timeout without going to operator voicemail.

Is there a way to disable this?

**Comment by lboom** [comment]
http://www.voip-info.org/wiki/view/Asterisk+config+features.conf

Looking at info for Blindxfer gives some insight to this. Could be a useful feature if we are able to transfer callers reliably.

**Comment by kra** [comment]
playing with it last night gave us lines like:

Mar 17 18:24:36] WARNING[2801][C-00000058] features.c: Extension '99' does not exist in context 'followme-operator'

so that's the context, we could add destinations there. We're in some kind of dialtone app like DISA or something? So we could add an i extension but probably not an instant menu? Don't know why it's failing on 2 digits, the extensions that are in there are 667 and 1+10 digit.

**Comment by lboom** [comment]
We can't currently do 3 way attended transfer to guide callers through a call.
