### ISSUE TITLE
add call a random payphone menu option

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#64]
we have the technology

**Comment by mihow** [comment]
👍

**Comment by kra** [comment]
https://www.google.com/maps/d/u/0/edit?mid=1uHkunWDa8tWeRSZfg2-k8hHUN6o

**Comment by kra** [comment]
good
503-591-9904
503-844-4814
503-640-9974

unknown
503-652-9829
503-648-8136
503-636-9093
503-636-9084
503-639-9912
503-579-8819
503-590-1924
503-590-1923
503-684-9520
503-684-9460
503-639-9958
503-684-9951
503-639-9904
503-684-9916
503-639-9959
503-598-9904
503-620-9900
503-639-9999
503-639-9987
503-639-9949
503-293-9772
503-692-5862
503-692-8456
503-682-7808
503-682-8025
503-682-9197

**Comment by Brandon314** [comment]
Sorry I haven't updated that map in awhile. Anyone is welcome to adjust it
if a payphone is near them and they want to test if it has inbound dialing
enabled. Different colors/symbols for different levels of conformation. See
notes on each phone for anything special.


Brandon M
Central Services - Telecom Division
brandon@centraltelco.com
http://centraltelco.com

**Comment by kra** [comment]
Sorry, I had to cut and paste from the webpage to get a text file, so I'm not able to update the original.

Horrible attrition!

**Comment by kra** [comment]
http://www.payphone-directory.org/payor.html
