### ISSUE TITLE
libresample build broken

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#73]
==> default: + pushd libresample-0.1.3
==> default: + ./configure
==> default: checking for gcc... 
==> default: gcc
==> default: checking for C compiler default output... 
==> default: a.out
==> default: checking whether the C compiler works... 
==> default: yes
==> default: checking whether we are cross compiling... no
==> default: checking for executable suffix... 
==> default: checking for object suffix... 
==> default: o
==> default: checking whether we are using the GNU C compiler... 
==> default: yes
==> default: checking whether gcc accepts -g... 
==> default: yes
==> default: checking for ranlib... ranlib
==> default: checking for ar... /usr/bin/ar
==> default: checking for sf_open in -lsndfile... 
==> default: yes
==> default: checking for src_simple in -lsamplerate... 
==> default: yes
==> default: checking how to run the C preprocessor... 
==> default: gcc -E
==> default: checking for inttypes.h... 
==> default: yes
==> default: configure: creating ./config.status
==> default: config.status: creating Makefile
==> default: config.status: creating src/config.h
==> default: 
==> default: Configured to build tests/resample-sndfile using libsndfile
==> default: 
==> default: Configured to build tests/compareresample to compare against
==> default: Erik de Castro Lopo's libsamplerate library.
==> default: 
==> default: Type 'configure --help' to see options.
==> default: 
==> default: Type 'make' to build libresample and tests.
==> default: + make
==> default: gcc -c -g -O2 -Wall src/resample.c -o src/resample.c.o
==> default: gcc -c -g -O2 -Wall src/resamplesubs.c -o src/resamplesubs.c.o
==> default: gcc -c -g -O2 -Wall src/filterkit.c -o src/filterkit.c.o
==> default: /usr/bin/ar ruv libresample.a src/resample.c.o src/resamplesubs.c.o src/filterkit.c.o
==> default: /usr/bin/ar: 
==> default: creating libresample.a
==> default: a - src/resample.c.o
==> default: a - src/resamplesubs.c.o
==> default: a - src/filterkit.c.o
==> default: ranlib libresample.a
==> default: gcc -o tests/testresample \
==> default: 		-g -O2 -Wall ./tests/testresample.c \
==> default: 		libresample.a -lm
==> default: gcc -o tests/resample-sndfile \
==> default: 		-g -O2 -Wall ./tests/resample-sndfile.c \
==> default: 		libresample.a -lsndfile -lm
==> default: gcc -o tests/compareresample \
==> default: 		-g -O2 -Wall ./tests/compareresample.c \
==> default: 		libresample.a -lsamplerate -lm
==> default: + make install
==> default: make: *** 
==> default: No rule to make target `install'
==> default: .  Stop.

**Comment by x37v** [comment]
@kra looks like there is no make install target.. my script did a make && make install, but didn't care if the install worked, so just ditch the make install and you're good.

**Comment by x37v** [comment]
should be fixed in b4f5510 unless you're building somewhere other than asteriskserver/src/build/make_asteriskbox.sh

**Comment by kra** [comment]
lack of resample breaks asterisk build, temporarily commented out
https://github.com/kra/futel-installation/commit/3134b87b68a5aaf4c59e38f2c008fbe5e9df9841
