### ISSUE TITLE
start default outgoing with tone

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#74]
outgoing-ivr begins with 0.25s of silence, then there's a very small pause at the beginning of the statement. Some people are impatient and think the phone does not work. Play a short tone like a 0.25s or 0.5s fading dialtone, or an 0.25s DTMF tone or two, or 0.5s both.

**Comment by lboom** [comment]
https://github.com/kra/futel-installation/commit/d79367aeb3534049a484e6494e60b3f0dc302caf
Adds some tones, we may wish to change these, but for now it makes it clear that the phone is working.
