### ISSUE TITLE
random number needs to handle keypresses

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#90]
```
[Jul 29 20:41:12] WARNING[3840][C-00000cf9] pbx.c: Invalid extension '6', but no rule 'i' or 'e' in context 'random-number'
```

user probably got disconnected after pressing a key

**Comment by kra** [comment]
should probably ignore all keypresses but return from gosub on #

**Comment by lboom** [comment]
Handling invalid keypresses by redirecting to random number menu.
